model_params:
  name: 'CelebA'
  in_channels: 3
  hidden_dims: null
  latent_dim: 64


data_params:
  data_path: "Data/"
  train_batch_size: 64
  val_batch_size:  64
  patch_size: 64
  num_workers: 4


exp_params:
  LR: 0.00005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 1
  recon_weight: 1      # Reconstruction weight
  reg_weight: 110  # MMD weight
  kernel_type: 'imq'
  alpha: -9.0     

trainer_params:
  gpus: [1]
  n_epochs: 5

logging_params:
  save_dir: "logs/"
  name: "InfoVAE"

dataset: "CelebA"
